(set _G.VSCodeNotify vim.fn.VSCodeNotify)
(set _G.VSCodeNotifyVisual vim.fn.VSCodeNotifyVisual)
(set _G.VSCodeCall vim.fn.VSCodeCall)
(set _G.VSCodeCallVisual vim.fn.VSCodeCallVisual)
(set _G.VSCodeExtensionNotify vim.fn.VSCodeExtensionNotify)
(set _G.VSCodeExtensionCall vim.fn.VSCodeExtensionCall)
